# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171129_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='code',
            field=models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code'),
        ),
    ]
