# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
