# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20171130_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', unique=True, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='front_page_image',
            field=models.ImageField(upload_to='goods/images', verbose_name='单独的封面图，不从轮播图中取'),
        ),
    ]
