# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171129_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
        migrations.RenameModel(
            old_name='UserFavor',
            new_name='UserFav',
        ),
    ]
